name: Update README
 
on:
  schedule:
    - cron: "0 12 * * *" # 매 시간 정각에 실행
  push:
    branches:
      - main
 
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm start
      - run: echo "node_modules/" >> .gitignore
      - run: |
          git config --local user.name 'HGJin'
          git config --local user.email 'hgj7618@naver.com'
      - id: check_changes
        run: echo ::set-output name=files_changed::$(git status --porcelain)
      - if: ${{ steps.check_changes.outputs.files_changed != '' }}
        run: |
          git add README.md
          git commit -m 'Update README with latest blog posts'
          git push origin HEAD:main
        env:
          GH_PERSONAL_TOKEN: ${{ secrets.repo_token }}
